package de.dumischbaenger.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-04T12:13:10.566+02:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "ExchangeWebService", 
                  wsdlLocation = "file:/home/bdonauba/git/ews-example/src/main/resources/META-INF/wsdl/ews.wsdl",
                  targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages") 
public class ExchangeWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://schemas.microsoft.com/exchange/services/2006/messages", "ExchangeWebService");
    public final static QName ExchangeWebPort = new QName("http://schemas.microsoft.com/exchange/services/2006/messages", "ExchangeWebPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/bdonauba/git/ews-example/src/main/resources/META-INF/wsdl/ews.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ExchangeWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/bdonauba/git/ews-example/src/main/resources/META-INF/wsdl/ews.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ExchangeWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExchangeWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExchangeWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ExchangeWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ExchangeWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ExchangeWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ExchangeServicePortType
     */
    @WebEndpoint(name = "ExchangeWebPort")
    public ExchangeServicePortType getExchangeWebPort() {
        return super.getPort(ExchangeWebPort, ExchangeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExchangeServicePortType
     */
    @WebEndpoint(name = "ExchangeWebPort")
    public ExchangeServicePortType getExchangeWebPort(WebServiceFeature... features) {
        return super.getPort(ExchangeWebPort, ExchangeServicePortType.class, features);
    }

}
